import { Link } from 'react-router-dom';
import { useCart } from '../context/useCart';

function Bag() {
  const { items, updateQuantity, removeFromCart } = useCart();
  const subtotal = items.reduce((sum, item) => sum + item.fullPrice * (1 - item.discountPercent / 100) * item.quantity, 0);

  return <main className="min-h-screen bg-gray-50 pt-32"><div className="mx-auto max-w-7xl px-5 py-8"><h1 className="mb-7 text-4xl font-bold">Shopping Bag</h1>{!items.length ? <div className="rounded-3xl bg-white p-12 text-center shadow-sm"><i className="bi bi-bag text-5xl text-gray-300" /><p className="mt-4 text-lg text-gray-500">Your bag is empty.</p><Link to="/shopall" className="mt-5 inline-block rounded-full bg-red-500 px-6 py-3 font-medium text-white">Continue shopping</Link></div> : <div className="grid gap-7 lg:grid-cols-[1fr_380px]"><section className="space-y-4">{items.map((item) => { const price = item.fullPrice * (1 - item.discountPercent / 100); return <article key={`${item.id}-${item.size}`} className="flex gap-4 rounded-2xl bg-white p-4 shadow-sm"><img className="h-28 w-28 rounded-xl bg-gray-50 object-contain" src={item.src} alt={item.alt} /><div className="min-w-0 flex-1"><h2 className="font-semibold">{item.title}</h2><p className="mt-1 text-sm text-gray-500">{item.size}ml</p><p className="mt-2 font-bold text-red-500">${price.toFixed(2)}</p><div className="mt-3 flex items-center justify-between"><div className="rounded-lg bg-gray-100"><button onClick={() => updateQuantity(item.id, item.size, item.quantity - 1)} className="px-3 py-1">−</button><span className="px-2">{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.size, item.quantity + 1)} className="px-3 py-1">+</button></div><button aria-label={`Remove ${item.title}`} onClick={() => removeFromCart(item.id, item.size)} className="text-gray-400 hover:text-red-500"><i className="bi bi-trash3" /></button></div></div></article>; })}</section><aside className="h-fit rounded-3xl bg-white p-6 shadow-sm"><h2 className="border-b pb-4 text-2xl font-bold">Order Summary</h2><div className="flex justify-between py-5"><span>Subtotal</span><strong className="text-red-500">${subtotal.toFixed(2)}</strong></div><p className="border-t pt-4 text-sm text-emerald-600"><i className="bi bi-truck mr-2" />Delivery calculated at checkout</p><button className="mt-5 w-full rounded-full bg-red-500 py-3.5 font-semibold text-white">Checkout now</button></aside></div>}</div></main>;
}
export default Bag;
